config/routes.rb
Rails.application.routes.draw do
  root "posts#index"

  resources :posts do
    resources :comments
  end
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  has_one :user
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user

    has_many :comments, dependent: :destroy

    validates :user, presence: true
    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }
end
  

app/models/user.rb
class User < ApplicationRecord
    has_many :posts, dependent: :destroy
    validates :name, presence: true
    validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def not_found
        raise ActionController::RoutingError.new('Not Found! Are you sure you entered a valid path?')
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    begin
      user = User.find(comment_params[:commenter].to_i)
    rescue
      flash.alert = "User not found."
      redirect_to post_path(@post) and return
    end
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post), status: :see_other
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id]) rescue not_found
  end

  def new
    @post = Post.new
  end

  def create
    begin
      user = User.find(post_params[:user_id].to_i)
    rescue
      flash.alert = "User not found."
      redirect_to new_post_path and return
    end

    @post = Post.new(title:post_params[:title],body:post_params[:body],user:user)

    if @post.save
      redirect_to post_path(@post)
    else
      render :new, status: :unprocessable_entity
    end
  end



  def edit
    @post = Post.find(params[:id]) rescue not_found
  end

  def update
    @post = Post.find(params[:id]) rescue not_found

    if @post.update(post_params)
      redirect_to @post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id]) rescue not_found
    @post.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def post_params
      params.require(:post).permit(:title, :body, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
      @users = User.all
    end
  
    def show
      @user = User.find(params[:id]) rescue not_found
    end
  
    def new
      @user = User.new
    end
  
    def create
      @user = User.new(user_params)
  
      if @user.save
        redirect_to @user
      else
        render :new, status: :unprocessable_entity
      end
    end
    def edit
      @user = User.find(params[:id]) rescue not_found
    end
  
    def update
      @user = User.find(params[:id]) rescue not_found
  
      if @user.update(user_params)
        redirect_to @user
      else
        render :edit, status: :unprocessable_entity
      end
    end
  
    def destroy
      @user = User.find(params[:id]) rescue not_found
      @user.posts.destroy
      @user.destroy
  
      redirect_to users_path, status: :see_other
    end
  
    private
      def user_params
        params.require(:user).permit(:name, :bio, :email)
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    Comment:
    <%= comment.body %>
  </p>
  <p>
    <%= link_to "Delete", [comment.post, comment], data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %>
  </p>

app/views/comments/_form.html.erb
<%= form_with model: [ @post, @post.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <% flash.each do |type, msg| %>
    <div>
      <%= msg %>
    </div>
  <% end %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CS291Project3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: post do |form| %>

  <div>
    <%= form.label :user_id %><br>
    <%= form.text_field :user_id %>
    <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% post.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% post.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "form", post: @post %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<ul>
  <% @posts.each do |post| %>
    <li>
      <%= link_to post.title, post %>
    </li>
  <% end %>
</ul>

<%= link_to "New Post", new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "form", post: @post %>

app/views/posts/show.html.erb
<h2>Post title: <%= @post.title %></h2>
<h4>Author: <%= @post.user.name %></h4>
<p>Content: <%= @post.body %></p>



<p>
  <%= link_to "Update", edit_post_path(@post) %> |
  <%= link_to "Delete", post_path(@post), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %> |
  <%= link_to "All Posts", posts_path %>
</p>

<h3>Comments</h3>
<%= render @post.comments %>

<h3>Add a comment:</h3>
<%= render 'comments/form' %>

app/views/users/_form.html.erb
<%= form_with model: user do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% user.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %><br>
    <% user.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render "form", user: @user %>

app/views/users/index.html.erb
<h1>Users</h1>

<ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

<%= link_to "New User", new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<h1>User Name: <%= @user.name %></h1>

<p>Email: <%= @user.email %></p>

<h2>Your Posts</h2>
<ul>
  <% @user.posts.each do |post| %>
    <li>
    <%= link_to post.title, post %>
    </li>
  <% end %>
</ul>

<h2>Other Actions</h2>
<ul>
  <li><%= link_to "Edit User", edit_user_path(@user) %></li>
  <li><%= link_to "Delete User", user_path(@user), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure? All corresponding posts will be deleted."
                  } %></li>
  <li><%= link_to "All Users", users_path %></li>
</ul>